### ISSUE TITLE
Adding images to developer guide

### ISSUE THREAD

**Issue by jialerk** [AY2021S1-CS2113T-W13-1/tp#85]
![AddSubjectSequenceDiagram](https://user-images.githubusercontent.com/47527482/98213500-1c89cd00-1f80-11eb-9b0c-9da37446b530.png)
![AccessSubjectSequenceDiagram](https://user-images.githubusercontent.com/47527482/98199431-171f8900-1f66-11eb-9dfe-fc263ccfe15f.png)
![TaskCommandClassDiagram](https://user-images.githubusercontent.com/47527482/97393705-211a0a00-191e-11eb-9546-f6b6b0e47bc4.png)
![FlashcardCommandClassDiagram](https://user-images.githubusercontent.com/47527482/97393768-24ad9100-191e-11eb-8f35-c7ed86d3dd55.png)
![SorrySubjectSequenceDiagram](https://user-images.githubusercontent.com/47527482/98226752-6a5b0100-1f91-11eb-8c11-7963c63dc69c.png)
![SorryTopicSequenceDiagram](https://user-images.githubusercontent.com/47527482/98228071-105b3b00-1f93-11eb-827f-80723a24bfe9.png)
![SubjectCommandClassDiagram](https://user-images.githubusercontent.com/47527482/98504305-9c21df80-2291-11eb-988a-916430c7270d.jpg)
![TopicCommandClassDiagram](https://user-images.githubusercontent.com/47527482/98504309-9fb56680-2291-11eb-932d-2ffac059b101.jpg)
![FlashcardCommandClassDiagram](https://user-images.githubusercontent.com/47527482/98503810-6cbea300-2290-11eb-90c3-e0525258077b.png)
![TaskCommandClassDiagram](https://user-images.githubusercontent.com/47527482/98503905-9e376e80-2290-11eb-90b8-274623ec400b.png)

**Comment by syncode98** [comment]
Used this issue to upload images.
