### ISSUE TITLE
Some comments on your DG.

### ISSUE THREAD

**Issue by Mick609** [AY2021S1-CS2113T-W13-1/tp#91]
1. Maybe it is better to describe the design of the system with class diagrams instead of only text. i.e., class diagrams presenting classes for different packages.

2. Isn't objects in the sequence diagram should have the colon before the name?
<img width="761" alt="Screen Shot 2020-10-30 at 1 43 55 PM" src="https://user-images.githubusercontent.com/28510345/97665465-696c3000-1ab6-11eb-952f-aac4154a6237.png">

3. Is the name of the method calling in the sequence diagram should be in double quote marks? Isn't the calling method line should be dashed?
<img width="775" alt="Screen Shot 2020-10-30 at 1 49 02 PM" src="https://user-images.githubusercontent.com/28510345/97665655-f7e0b180-1ab6-11eb-8f9d-f0e93b748512.png">

4. Maybe an object diagram would be a better choice for illustrating the relationship between data storage and each class (or object).
<img width="587" alt="Screen Shot 2020-10-30 at 1 54 28 PM" src="https://user-images.githubusercontent.com/28510345/97665927-8e14d780-1ab7-11eb-86ee-b1a35445707e.png">

5. It would be better if you can specify the caller of the method loadTopics(topicFolders) and the body that receives the return value of topics in the reference frame. I am also confused about the reference frame shown here. Do you guys mean that when the system loads subjects, the storage class calls a loadTopics(topicFolders) method for each subject, then this loadTopics(topicFolders) call the same loadTopics() method for topics? The name loadTopic is a bit misleading.
<img width="620" alt="Screen Shot 2020-10-30 at 1 57 19 PM" src="https://user-images.githubusercontent.com/28510345/97666537-df719680-1ab8-11eb-939a-082a1795a1ec.png">

**Comment by CookieHoodie** [comment]
Other than 3, others are solved
